# Generated by Django 4.0.2 on 2022-02-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complex_farm_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.PositiveIntegerField()),
                ('posY', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('hour', models.PositiveIntegerField()),
                ('events_1', models.PositiveIntegerField()),
                ('events_2', models.PositiveIntegerField()),
                ('events_3', models.PositiveIntegerField()),
                ('events_4', models.PositiveIntegerField()),
                ('events_5', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
        ),
    ]
