# Generated by Django 4.0.2 on 2022-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monitor_hourlydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('events_1', models.PositiveIntegerField()),
                ('events_2', models.PositiveIntegerField()),
                ('events_3', models.PositiveIntegerField()),
                ('events_4', models.PositiveIntegerField()),
                ('events_5', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
        ),
    ]
