# Generated by Django 4.0.2 on 2022-02-11 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_dailydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
        migrations.AddField(
            model_name='complex',
            name='name',
            field=models.CharField(default='Complex A', max_length=30),
        ),
        migrations.AddField(
            model_name='complex',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
