# Generated by Django 4.0.2 on 2022-02-13 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_alter_dailydata_monitor_alter_hourlydata_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isFarmer', models.BooleanField(default=False)),
            ],
        ),
    ]
