# Generated by Django 4.0.2 on 2022-02-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='isIntegrator',
            field=models.BooleanField(default=False),
        ),
    ]
