# Generated by Django 4.0.2 on 2022-02-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usertype_isintegrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.complex'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
