# Generated by Django 4.0.2 on 2022-02-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_complex_user_alter_farm_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyData',
        ),
    ]
