# Generated by Django 4.0.2 on 2022-02-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_dailydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='name',
        ),
    ]
