# Generated by Django 4.0.2 on 2022-02-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_monitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(default='Farm A', max_length=30),
        ),
        migrations.AlterField(
            model_name='farm',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='core.complex'),
        ),
    ]
