# Generated by Django 4.0.2 on 2022-02-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_farm_name_alter_farm_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.farm'),
        ),
    ]
