# Generated by Django 4.0.2 on 2022-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_house_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lastFlockEntry',
            field=models.DateField(null=True),
        ),
    ]
