# Generated by Django 4.0.2 on 2022-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_house_lastflockentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'None'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Severe')], default=0),
        ),
    ]
