# Generated by Django 4.0.2 on 2022-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(default='Monitor A', max_length=30),
        ),
    ]
