# Generated by Django 4.0.2 on 2022-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_hourlydata_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='status',
        ),
        migrations.RemoveField(
            model_name='house',
            name='monitorCount',
        ),
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
    ]
