# Generated by Django 4.0.2 on 2022-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_farm_status_remove_house_monitorcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='heatmapJson',
            field=models.JSONField(null=True),
        ),
    ]
