# Generated by Django 4.0.2 on 2022-03-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_house_heatmapjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('events_1', models.PositiveIntegerField()),
                ('events_2', models.PositiveIntegerField()),
                ('events_3', models.PositiveIntegerField()),
                ('events_4', models.PositiveIntegerField()),
                ('events_5', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monitor')),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='heatmapJson',
        ),
        migrations.DeleteModel(
            name='HourlyData',
        ),
    ]
