# Generated by Django 4.0.2 on 2022-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_data_remove_house_heatmapjson_delete_hourlydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='heatmap',
            field=models.ImageField(default='heatmaps/', upload_to='heatmaps/'),
        ),
    ]
