# Generated by Django 4.0.2 on 2022-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_house_heatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lastDataTimestampProcessed',
            field=models.DateTimeField(null=True),
        ),
    ]
