# Generated by Django 4.0.2 on 2022-04-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_house_lastdatatimestampprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='report',
            field=models.FileField(default='reports/', upload_to='reports/'),
        ),
    ]
